INFO:root:load_data. dataset_name = mnist
Traceback (most recent call last):
  File "./main_fedavg.py", line 305, in <module>
    dataset = load_data(args, args.dataset)
  File "./main_fedavg.py", line 110, in load_data
    class_num = load_partition_data_mnist(args.batch_size)
  File "/home/workspace/FedML/fedml_api/data_preprocessing/MNIST/data_loader.py", line 90, in load_partition_data_mnist
    users, groups, train_data, test_data = read_data(train_path, test_path)
  File "/home/workspace/FedML/fedml_api/data_preprocessing/MNIST/data_loader.py", line 28, in read_data
    train_files = os.listdir(train_data_dir)
FileNotFoundError: [Errno 2] No such file or directory: './../../../data/MNIST/train'