2021-11-23 13:12:06,107 INFO    MainThread:14877 [wandb_setup.py:_flush():71] setting env: {}
2021-11-23 13:12:06,107 INFO    MainThread:14877 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-23 13:12:06,107 INFO    MainThread:14877 [wandb_init.py:_log_setup():371] Logging user logs to /home/cps/Desktop/FedML_CPS/fedml_experiments/standalone/fedavg/wandb/run-20211123_131206-18hcy936/logs/debug.log
2021-11-23 13:12:06,107 INFO    MainThread:14877 [wandb_init.py:_log_setup():372] Logging internal logs to /home/cps/Desktop/FedML_CPS/fedml_experiments/standalone/fedavg/wandb/run-20211123_131206-18hcy936/logs/debug-internal.log
2021-11-23 13:12:06,108 INFO    MainThread:14877 [wandb_init.py:init():404] calling init triggers
2021-11-23 13:12:06,108 INFO    MainThread:14877 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {'model': 'cnn', 'dataset': 'femnist', 'data_dir': './../../../data/FederatedEMNIST/datasets', 'partition_method': 'hetero', 'partition_alpha': 0.5, 'batch_size': 20, 'client_optimizer': 'sgd', 'lr': 0.03, 'wd': 0.001, 'epochs': 1, 'client_num_in_total': 10, 'client_num_per_round': 10, 'comm_round': 1000, 'frequency_of_the_test': 5, 'interver': 5, 'gpu': 0, 'ci': 0}
2021-11-23 13:12:06,108 INFO    MainThread:14877 [wandb_init.py:init():449] starting backend
2021-11-23 13:12:06,108 INFO    MainThread:14877 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-11-23 13:12:06,122 INFO    MainThread:14877 [backend.py:ensure_launched():199] starting backend process...
2021-11-23 13:12:06,126 INFO    MainThread:14877 [backend.py:ensure_launched():204] started backend process with pid: 14893
2021-11-23 13:12:06,128 INFO    MainThread:14877 [wandb_init.py:init():458] backend started and connected
2021-11-23 13:12:06,130 INFO    MainThread:14877 [wandb_init.py:init():519] updated telemetry
2021-11-23 13:12:06,143 INFO    MainThread:14877 [wandb_init.py:init():549] communicating current version
2021-11-23 13:12:06,920 INFO    MainThread:14877 [wandb_init.py:init():554] got version response 
2021-11-23 13:12:06,921 INFO    MainThread:14877 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-11-23 13:12:07,161 INFO    MainThread:14877 [wandb_init.py:init():592] starting run threads in backend
2021-11-23 13:12:07,584 WARNING MainThread:14877 [wandb_init.py:init():938] interrupted
Traceback (most recent call last):
  File "/home/cps/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 917, in init
    run = wi.init()
  File "/home/cps/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 597, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/home/cps/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 216, in communicate_run_start
    result = self._communicate_run_start(run_start)
  File "/home/cps/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface_queue.py", line 446, in _communicate_run_start
    result = self._communicate(rec)
  File "/home/cps/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface_queue.py", line 232, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/cps/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/router.py", line 32, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/cps/anaconda3/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/home/cps/anaconda3/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
